[package]
name = "pebble-sys"
version = "0.1.0-dev+4.9.169"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2024"
description = "Low-level FFI bindings for Pebble watches"
license = "Apache-2.0"
repository = "https://github.com/Tamschi/pebble-sys"
homepage = "https://github.com/Tamschi/pebble-sys/tree/v0.0.1"
documentation = "https://docs.rs/pebble-sys/0.0.1"
keywords = ["Pebble", "watch", "embedded", "FFI", "bindings"]
categories = ["hardware-support"]
readme = "README.md"
include = [
	"**/*.rs",
	"!tests/unincluded_*.rs",    # Tests of meta data files not included in the package.
	"Cargo.toml",
	"CHANGELOG.md",
	"CODE_OF_CONDUCT.md",
	"LICENSE",
	"README.md",
	"thumbv7m-pebble-eabi.json",
]
publish = false

[features]
panic_handler = [] # Provides a #[panic_handler] implementation.
