//! Managing application resources
//!
//! Resources are data files that are bundled with your application binary and can be loaded at runtime.
//! You use resources to embed images or custom fonts in your app, but also to embed any data file. Resources are always read-only.
//!
//! Resources are stored on Pebble’s flash memory and only loaded in RAM when you load them.
//! This means that you can have a large number of resources embedded inside your app, even though Pebble’s RAM memory is very limited.
//!
//! See [App Resources in the Pebble Developer Guides](https://developer.getpebble.com/guides/pebble-apps/resources/)
//! for information on how to embed resources into your app's bundle.

use core::ffi::c_void;

#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
/// Opaque reference to a resource.
///
/// # See also
///
/// - [`resource_get_handle()`]
pub struct ResHandle(pub *const c_void);

unsafe extern "C" {
	/// Gets the resource handle for a file identifier.
	///
	/// The resource IDs are auto-generated by the Pebble build process, based on the `appinfo.json`.
	/// The "name" field of each resource is prefixed by `RESOURCE_ID_` and made visible to the application
	/// (through the `build/src/resource_ids.auto.h` header which is automatically included).
	///
	/// For example, given the following fragment of `appinfo.json`:
	///
	/// ```json
	/// ...
	/// "resources" : {
	/// "media": [
	///      {
	///         "name": "MY_ICON",
	///         "file": "img/icon.png",
	///         "type": "png",
	///      },
	///  ...
	/// ```
	///
	/// The generated file identifier for this resource is RESOURCE_ID_MY_ICON.
	/// To get a resource handle for that resource write:
	///
	/// ```c
	/// // C
	/// ResHandle rh = resource_get_handle(RESOURCE_ID_MY_ICON);
	/// ```
	pub fn resource_get_handle(resource_id: u32) -> ResHandle;

	/// Gets the size of the resource given a resource handle.
	pub fn resource_size(h: ResHandle) -> usize;

	/// Copies the bytes for the resource with a given handle from flash storage into a given buffer.
	///
	/// # Returns
	///
	/// The number of bytes actually copied
	pub fn resource_load(h: ResHandle, buffer: *mut u8, max_length: usize) -> usize;

	/// Copies a range of bytes from a resource with a given handle into a given buffer.
	///
	/// # Returns
	///
	/// The number of bytes actually copied
	pub fn resource_load_byte_range(
		h: ResHandle,
		start_offset: u32,
		buffer: *mut u8,
		num_bytes: usize,
	) -> usize;
}
